/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_matlabfind (void)
{
  GtkWidget *matlabfind;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *quit1;
  GtkWidget *scopeMenu;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkWidget *about1;
  GtkWidget *notebook1;
  GtkWidget *hbox15;
  GtkWidget *vbox13;
  GtkWidget *frame7;
  GtkWidget *alignment17;
  GtkWidget *table2;
  GtkWidget *label47;
  GtkWidget *hbox17;
  GtkWidget *evalFunction;
  GtkWidget *label46;
  GtkWidget *initFunction;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *threshold;
  GtkWidget *srcFolder;
  GtkWidget *label34;
  GtkWidget *hbox18;
  GtkWidget *vbox17;
  GtkWidget *hbox20;
  GtkWidget *searchName;
  GtkWidget *saveSearchButton;
  GtkWidget *label25;
  GtkWidget *vpaned1;
  GtkWidget *vbox19;
  GtkWidget *hbox19;
  GtkWidget *frame12;
  GtkWidget *alignment22;
  GtkWidget *vbox16;
  GtkWidget *scrolledwindow10;
  GtkWidget *definedSearches;
  GtkWidget *hbuttonbox2;
  GtkWidget *startSearch;
  GtkWidget *alignment25;
  GtkWidget *hbox22;
  GtkWidget *image2;
  GtkWidget *label43;
  GtkWidget *label40;
  GtkWidget *frame13;
  GtkWidget *alignment23;
  GtkWidget *vbox19;
  GtkWidget *scrolledwindow11;
  GtkWidget *searchResults;
  GtkWidget *hbuttonbox3;
  GtkWidget *stopSearch;
  GtkWidget *alignment24;
  GtkWidget *hbox21;
  GtkWidget *image1;
  GtkWidget *label42;
  GtkWidget *clearSearch;
  GtkWidget *label41;
  GtkWidget *statsLabel;
  GtkWidget *frame14;
  GtkWidget *alignment26;
  GtkWidget *table3;
  GtkWidget *selectedResult;
  GtkWidget *resultVRuler;
  GtkWidget *resultHRuler;
  GtkWidget *label44;
  GtkWidget *label26;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  matlabfind = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (matlabfind), "MATLABFind");
  gtk_window_set_default_size (GTK_WINDOW (matlabfind), 800, 600);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (matlabfind), TRUE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (matlabfind), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic ("_File");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), quit1);

  scopeMenu = gtk_menu_item_new_with_mnemonic ("_Scope");
  gtk_widget_show (scopeMenu);
  gtk_container_add (GTK_CONTAINER (menubar1), scopeMenu);

  help1 = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar1), help1);

  help1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);

  about1 = gtk_image_menu_item_new_from_stock ("gtk-about", accel_group);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  hbox15 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (notebook1), hbox15);
  gtk_container_set_border_width (GTK_CONTAINER (hbox15), 2);

  vbox13 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox13);
  gtk_box_pack_start (GTK_BOX (hbox15), vbox13, TRUE, TRUE, 0);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox13), frame7, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame7), GTK_SHADOW_IN);

  alignment17 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (frame7), alignment17);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment17), 0, 0, 12, 0);

  table2 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (alignment17), table2);

  label47 = gtk_label_new ("Init function:");
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table2), label47, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_table_attach (GTK_TABLE (table2), hbox17, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  evalFunction = gtk_entry_new ();
  gtk_widget_show (evalFunction);
  gtk_box_pack_start (GTK_BOX (hbox17), evalFunction, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (evalFunction), 9679);

  label46 = gtk_label_new ("Eval function:");
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table2), label46, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label46), 0, 0.5);

  initFunction = gtk_entry_new ();
  gtk_widget_show (initFunction);
  gtk_table_attach (GTK_TABLE (table2), initFunction, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (initFunction), 9679);

  label48 = gtk_label_new ("Source folder:");
  gtk_widget_show (label48);
  gtk_table_attach (GTK_TABLE (table2), label48, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label48), 0, 0.5);

  label49 = gtk_label_new ("Threshold:");
  gtk_widget_show (label49);
  gtk_table_attach (GTK_TABLE (table2), label49, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label49), 0, 0.5);

  threshold = gtk_entry_new ();
  gtk_widget_show (threshold);
  gtk_table_attach (GTK_TABLE (table2), threshold, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (threshold), 9679);

  srcFolder = gtk_file_chooser_button_new ("Select A Folder", GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (srcFolder);
  gtk_table_attach (GTK_TABLE (table2), srcFolder, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label34 = gtk_label_new ("<b>Parameters</b>");
  gtk_widget_show (label34);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label34);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox18, TRUE, TRUE, 0);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox17);
  gtk_box_pack_start (GTK_BOX (hbox18), vbox17, TRUE, TRUE, 0);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox20);
  gtk_box_pack_end (GTK_BOX (vbox17), hbox20, FALSE, TRUE, 0);

  searchName = gtk_entry_new ();
  gtk_widget_show (searchName);
  gtk_box_pack_start (GTK_BOX (hbox20), searchName, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (searchName), 8226);
  gtk_entry_set_activates_default (GTK_ENTRY (searchName), TRUE);

  saveSearchButton = gtk_button_new_from_stock ("gtk-save-as");
  gtk_widget_show (saveSearchButton);
  gtk_box_pack_start (GTK_BOX (hbox20), saveSearchButton, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (saveSearchButton, FALSE);
  GTK_WIDGET_SET_FLAGS (saveSearchButton, GTK_CAN_DEFAULT);

  label25 = gtk_label_new_with_mnemonic ("_Define Searchlet");
  gtk_widget_show (label25);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label25);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_show (vpaned1);
  gtk_container_add (GTK_CONTAINER (notebook1), vpaned1);
  gtk_paned_set_position (GTK_PANED (vpaned1), 283);

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox19);
  gtk_paned_pack1 (GTK_PANED (vpaned1), vbox19, FALSE, TRUE);

  hbox19 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox19), hbox19, TRUE, TRUE, 0);

  frame12 = gtk_frame_new (NULL);
  gtk_widget_show (frame12);
  gtk_box_pack_start (GTK_BOX (hbox19), frame12, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame12), GTK_SHADOW_IN);

  alignment22 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (frame12), alignment22);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment22), 0, 0, 12, 0);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox16);
  gtk_container_add (GTK_CONTAINER (alignment22), vbox16);

  scrolledwindow10 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow10);
  gtk_box_pack_start (GTK_BOX (vbox16), scrolledwindow10, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow10), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow10), GTK_SHADOW_IN);

  definedSearches = gtk_tree_view_new ();
  gtk_widget_show (definedSearches);
  gtk_container_add (GTK_CONTAINER (scrolledwindow10), definedSearches);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox16), hbuttonbox2, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_SPREAD);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox2), 40);

  startSearch = gtk_button_new ();
  gtk_widget_show (startSearch);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), startSearch);
  GTK_WIDGET_SET_FLAGS (startSearch, GTK_CAN_DEFAULT);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (startSearch), alignment25);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox22);

  image2 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox22), image2, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic ("Begin Search");
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox22), label43, FALSE, FALSE, 0);

  label40 = gtk_label_new ("<b>Defined Searches</b>");
  gtk_widget_show (label40);
  gtk_frame_set_label_widget (GTK_FRAME (frame12), label40);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  frame13 = gtk_frame_new (NULL);
  gtk_widget_show (frame13);
  gtk_box_pack_start (GTK_BOX (hbox19), frame13, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame13), GTK_SHADOW_IN);

  alignment23 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (frame13), alignment23);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment23), 0, 0, 12, 0);

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox19);
  gtk_container_add (GTK_CONTAINER (alignment23), vbox19);

  scrolledwindow11 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow11);
  gtk_box_pack_start (GTK_BOX (vbox19), scrolledwindow11, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow11), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow11), GTK_SHADOW_IN);

  searchResults = gtk_icon_view_new ();
  gtk_widget_show (searchResults);
  gtk_container_add (GTK_CONTAINER (scrolledwindow11), searchResults);
  gtk_icon_view_set_selection_mode (GTK_ICON_VIEW (searchResults), GTK_SELECTION_BROWSE);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox19), hbuttonbox3, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_SPREAD);

  stopSearch = gtk_button_new ();
  gtk_widget_show (stopSearch);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), stopSearch);
  gtk_widget_set_sensitive (stopSearch, FALSE);
  GTK_WIDGET_SET_FLAGS (stopSearch, GTK_CAN_DEFAULT);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (stopSearch), alignment24);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox21);

  image1 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox21), image1, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic ("Stop Search");
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox21), label42, FALSE, FALSE, 0);

  clearSearch = gtk_button_new_from_stock ("gtk-clear");
  gtk_widget_show (clearSearch);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), clearSearch);
  GTK_WIDGET_SET_FLAGS (clearSearch, GTK_CAN_DEFAULT);

  label41 = gtk_label_new ("<b>Search Results</b>");
  gtk_widget_show (label41);
  gtk_frame_set_label_widget (GTK_FRAME (frame13), label41);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  statsLabel = gtk_label_new ("");
  gtk_widget_show (statsLabel);
  gtk_box_pack_start (GTK_BOX (vbox19), statsLabel, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (statsLabel), 0, 0.5);

  frame14 = gtk_frame_new (NULL);
  gtk_widget_show (frame14);
  gtk_paned_pack2 (GTK_PANED (vpaned1), frame14, TRUE, TRUE);
  gtk_frame_set_shadow_type (GTK_FRAME (frame14), GTK_SHADOW_IN);

  alignment26 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (frame14), alignment26);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment26), 0, 0, 12, 0);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (alignment26), table3);

  selectedResult = gtk_drawing_area_new ();
  gtk_widget_show (selectedResult);
  gtk_table_attach (GTK_TABLE (table3), selectedResult, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_events (selectedResult, GDK_POINTER_MOTION_MASK | GDK_BUTTON1_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK);

  resultVRuler = gtk_vruler_new ();
  gtk_widget_show (resultVRuler);
  gtk_table_attach (GTK_TABLE (table3), resultVRuler, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_ruler_set_range (GTK_RULER (resultVRuler), 0, 10, 0, 10);

  resultHRuler = gtk_hruler_new ();
  gtk_widget_show (resultHRuler);
  gtk_table_attach (GTK_TABLE (table3), resultHRuler, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_ruler_set_range (GTK_RULER (resultHRuler), 0, 10, 6.10236, 10);

  label44 = gtk_label_new ("<b>Selected Result</b>");
  gtk_widget_show (label44);
  gtk_frame_set_label_widget (GTK_FRAME (frame14), label44);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  label26 = gtk_label_new_with_mnemonic ("_Investigate");
  gtk_widget_show (label26);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label26);

  g_signal_connect ((gpointer) matlabfind, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) searchName, "changed",
                    G_CALLBACK (on_searchName_changed),
                    NULL);
  g_signal_connect ((gpointer) saveSearchButton, "clicked",
                    G_CALLBACK (on_saveSearchButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) startSearch, "clicked",
                    G_CALLBACK (on_startSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) searchResults, "selection_changed",
                    G_CALLBACK (on_searchResults_selection_changed),
                    NULL);
  g_signal_connect ((gpointer) stopSearch, "clicked",
                    G_CALLBACK (on_stopSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) clearSearch, "clicked",
                    G_CALLBACK (on_clearSearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) selectedResult, "expose_event",
                    G_CALLBACK (on_selectedResult_expose_event),
                    NULL);
  g_signal_connect ((gpointer) selectedResult, "button_press_event",
                    G_CALLBACK (on_selectedResult_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) selectedResult, "button_release_event",
                    G_CALLBACK (on_selectedResult_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) selectedResult, "motion_notify_event",
                    G_CALLBACK (on_selectedResult_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) selectedResult, "configure_event",
                    G_CALLBACK (on_selectedResult_configure_event),
                    NULL);
  g_signal_connect ((gpointer) selectedResult, "enter_notify_event",
                    G_CALLBACK (on_selectedResult_enter_notify_event),
                    NULL);
  g_signal_connect ((gpointer) selectedResult, "leave_notify_event",
                    G_CALLBACK (on_selectedResult_leave_notify_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (matlabfind, matlabfind, "matlabfind");
  GLADE_HOOKUP_OBJECT (matlabfind, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (matlabfind, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (matlabfind, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (matlabfind, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (matlabfind, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (matlabfind, scopeMenu, "scopeMenu");
  GLADE_HOOKUP_OBJECT (matlabfind, help1, "help1");
  GLADE_HOOKUP_OBJECT (matlabfind, help1_menu, "help1_menu");
  GLADE_HOOKUP_OBJECT (matlabfind, about1, "about1");
  GLADE_HOOKUP_OBJECT (matlabfind, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (matlabfind, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (matlabfind, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (matlabfind, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (matlabfind, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (matlabfind, table2, "table2");
  GLADE_HOOKUP_OBJECT (matlabfind, label47, "label47");
  GLADE_HOOKUP_OBJECT (matlabfind, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (matlabfind, evalFunction, "evalFunction");
  GLADE_HOOKUP_OBJECT (matlabfind, label46, "label46");
  GLADE_HOOKUP_OBJECT (matlabfind, initFunction, "initFunction");
  GLADE_HOOKUP_OBJECT (matlabfind, label48, "label48");
  GLADE_HOOKUP_OBJECT (matlabfind, label49, "label49");
  GLADE_HOOKUP_OBJECT (matlabfind, threshold, "threshold");
  GLADE_HOOKUP_OBJECT (matlabfind, srcFolder, "srcFolder");
  GLADE_HOOKUP_OBJECT (matlabfind, label34, "label34");
  GLADE_HOOKUP_OBJECT (matlabfind, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (matlabfind, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (matlabfind, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (matlabfind, searchName, "searchName");
  GLADE_HOOKUP_OBJECT (matlabfind, saveSearchButton, "saveSearchButton");
  GLADE_HOOKUP_OBJECT (matlabfind, label25, "label25");
  GLADE_HOOKUP_OBJECT (matlabfind, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (matlabfind, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (matlabfind, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (matlabfind, frame12, "frame12");
  GLADE_HOOKUP_OBJECT (matlabfind, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (matlabfind, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (matlabfind, scrolledwindow10, "scrolledwindow10");
  GLADE_HOOKUP_OBJECT (matlabfind, definedSearches, "definedSearches");
  GLADE_HOOKUP_OBJECT (matlabfind, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (matlabfind, startSearch, "startSearch");
  GLADE_HOOKUP_OBJECT (matlabfind, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (matlabfind, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (matlabfind, image2, "image2");
  GLADE_HOOKUP_OBJECT (matlabfind, label43, "label43");
  GLADE_HOOKUP_OBJECT (matlabfind, label40, "label40");
  GLADE_HOOKUP_OBJECT (matlabfind, frame13, "frame13");
  GLADE_HOOKUP_OBJECT (matlabfind, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (matlabfind, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (matlabfind, scrolledwindow11, "scrolledwindow11");
  GLADE_HOOKUP_OBJECT (matlabfind, searchResults, "searchResults");
  GLADE_HOOKUP_OBJECT (matlabfind, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (matlabfind, stopSearch, "stopSearch");
  GLADE_HOOKUP_OBJECT (matlabfind, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (matlabfind, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (matlabfind, image1, "image1");
  GLADE_HOOKUP_OBJECT (matlabfind, label42, "label42");
  GLADE_HOOKUP_OBJECT (matlabfind, clearSearch, "clearSearch");
  GLADE_HOOKUP_OBJECT (matlabfind, label41, "label41");
  GLADE_HOOKUP_OBJECT (matlabfind, statsLabel, "statsLabel");
  GLADE_HOOKUP_OBJECT (matlabfind, frame14, "frame14");
  GLADE_HOOKUP_OBJECT (matlabfind, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (matlabfind, table3, "table3");
  GLADE_HOOKUP_OBJECT (matlabfind, selectedResult, "selectedResult");
  GLADE_HOOKUP_OBJECT (matlabfind, resultVRuler, "resultVRuler");
  GLADE_HOOKUP_OBJECT (matlabfind, resultHRuler, "resultHRuler");
  GLADE_HOOKUP_OBJECT (matlabfind, label44, "label44");
  GLADE_HOOKUP_OBJECT (matlabfind, label26, "label26");

  gtk_widget_grab_default (saveSearchButton);
  gtk_window_add_accel_group (GTK_WINDOW (matlabfind), accel_group);

  return matlabfind;
}

GtkWidget*
create_histogramWindow (void)
{
  GtkWidget *histogramWindow;
  GtkWidget *scrolledwindow12;
  GtkWidget *histogram;

  histogramWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (histogramWindow), "Histogram Report");
  gtk_window_set_default_size (GTK_WINDOW (histogramWindow), 400, 550);

  scrolledwindow12 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow12);
  gtk_container_add (GTK_CONTAINER (histogramWindow), scrolledwindow12);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow12), GTK_SHADOW_IN);

  histogram = gtk_text_view_new ();
  gtk_widget_show (histogram);
  gtk_container_add (GTK_CONTAINER (scrolledwindow12), histogram);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (histogram), FALSE);

  g_signal_connect ((gpointer) histogramWindow, "delete_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (histogramWindow, histogramWindow, "histogramWindow");
  GLADE_HOOKUP_OBJECT (histogramWindow, scrolledwindow12, "scrolledwindow12");
  GLADE_HOOKUP_OBJECT (histogramWindow, histogram, "histogram");

  return histogramWindow;
}

GtkWidget*
create_aboutdialog1 (void)
{
  GtkWidget *aboutdialog1;
  const gchar *authors[] = {
    "Jason Ganetsky <jganetsk@cs.cmu.edu>",
    "Adam Goode <agoode@andrew.cmu.edu>",
    NULL
  };

  aboutdialog1 = gtk_about_dialog_new ();
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog1), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog1), "MATLABFind");
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog1), "Copyright \302\251 2006-2007 Carnegie Mellon University");
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog1), "A Diamond application for interoperating with MATLAB.");
  gtk_about_dialog_set_license (GTK_ABOUT_DIALOG (aboutdialog1), "This program and the accompanying materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this distribution in the file named LICENSE.");
  gtk_about_dialog_set_wrap_license (GTK_ABOUT_DIALOG (aboutdialog1), TRUE);
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog1), authors);

  g_signal_connect ((gpointer) aboutdialog1, "delete_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog1, aboutdialog1, "aboutdialog1");

  return aboutdialog1;
}

