#!/usr/bin/env python
#
#  ImageJFind, a Diamond filter for interoperating with ImageJ
#
#  Copyright (c) 2011 Carnegie Mellon University
#  All rights reserved.
#
#  This software is distributed under the terms of the Eclipse Public
#  License, Version 1.0 which can be found in the file named LICENSE.
#  ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS SOFTWARE CONSTITUTES
#  RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT
#

import os
from opendiamond.bundle import bundle_macro
from optparse import OptionParser

if __name__ == '__main__':
    parser = OptionParser(
        usage='%prog [-h] [options] macro-file [supporting-files...]',
        description='Package a Diamond filter written in ImageJ into an OpenDiamond search bundle.',
    )
    parser.add_option('-o', dest='outfile', metavar='outfile',
            help='path to output file')
    parser.add_option('-n', dest='name', metavar='display-name',
            default='ImageJ Search',
            help='display name for search')
    opts, args = parser.parse_args()
    if len(args) < 1:
        parser.error('no macro file specified')
    macro_file = args[0]
    macro = os.path.basename(macro_file)
    outfile = opts.outfile
    if outfile is None:
        outfile = os.path.splitext(macro_file)[0] + '.search'

    try:
        bundle_macro(outfile, opts.name, 'fil_imagej_exec', [macro], args)
    except Exception, e:
        parser.error(str(e))
