all: data/filter/fil_imagej_exec.so

data/filter/fil_imagej_exec.so: src/fil_imagej_exec.c src/imagej-bin.h src/ijloader-bin.h src/diamond_filter-bin.h src/quick_tar.c src/quick_tar.h
	gcc -fPIC `pkg-config opendiamond glib-2.0 --cflags --libs` -O2 -g -m32 -Wall -shared  -o $@ src/fil_imagej_exec.c src/quick_tar.c


src/imagej-bin.h: ij140.zip src/encapsulate
	./src/encapsulate imagej_bin < $< > $@

src/ijloader-bin.h: ijloader.jar src/encapsulate
	./src/encapsulate ijloader_bin < $< > $@

src/diamond_filter-bin.h: diamond_filter.jar src/encapsulate
	./src/encapsulate diamond_filter_bin < $< > $@

src/encapsulate: src/encapsulate.c
	gcc -O2 -Wall -g $< -o $@


clean:
	$(RM) data/filter/fil_imagej_exec.so src/*-bin.h src/encapsulate
